phrase = input("Ecrivez une phrase : ")
print("Votre phrase en majuscule : " + phrase.upper())
print("Votre phrase en minuscule : " + phrase.lower())
lesMots = phrase.split()
print("Votre phrase contient : " + str(len(lesMots)) + " mots")